### ISSUE TITLE
Verilator PATH settings

### ISSUE THREAD

**Issue by apple9515** [poucotm/SublimeLinter-contrib-verilator#1]
Where is verilator_bin?Should I rename verilator?How to add PATH environment variable for verilator_bin in Windows10?Sorry,can you go into more detail?

**Comment by poucotm** [comment]
You did compile ? If do, you can find verilator_bin.exe.

**Comment by apple9515** [comment]
Thanks for your reply.I can't find install method or compile method in windows 10.It's all about linux method that I can find.Can you give me the detail or some links?

**Comment by poucotm** [comment]
Try MinGW, gcc for windows.

http://www.mingw.org/wiki/howto_install_the_mingw_gcc_compiler_suite

**Comment by apple9515** [comment]
Thank you for your patience.I already compiled by cygwin.And your tool is wonderful.If there are bugs I'll tell in time.Thank you again.
