### ISSUE TITLE
MATCH_DICT SublimeLinter

### ISSUE THREAD

**Issue by evgeniyBolnov** [poucotm/SublimeLinter-contrib-verilator#3]
In this commit https://github.com/SublimeLinter/SublimeLinter/commit/a8bb25cf955e7fd08d9594f49c29cba936d21faf MATCH_DICT has been deleted and therefore the plugin does not work :cry:

**Comment by evgeniyBolnov** [comment]
As a temporary solution:
```Python
from collections import OrderedDict
```

```Python        
match_dict = OrderedDict(
            (
                ("match", None),
                ("line", None),
                ("col", None),
                ("error", None),
                ("warning", None),
                ("message", ''),
                ("near", None)
            )
        )
```

**Comment by poucotm** [comment]
Thanks for information. Im on vacation. After back to home, I would check.

**Comment by poucotm** [comment]
@rash230691 I've updated codes, please, check with v2.3.7.

**Comment by evgeniyBolnov** [comment]
> @rash230691 I've updated codes, please, check with v2.3.7.

Thank you, it's work!
